# Generated by Django 3.2.10 on 2022-04-29 11:31

from django.db import migrations, models
import django.db.models.deletion
import tutorial.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Номер билета')),
                ('question', models.TextField(help_text='Вопрос', max_length=2000, verbose_name='Вопрос')),
                ('choice1', models.CharField(help_text='Вариант ответа', max_length=240, verbose_name='Вариант #1')),
                ('choice2', models.CharField(help_text='Вариант ответа', max_length=240, verbose_name='Вариант #2')),
                ('choice3', models.CharField(help_text='Вариант ответа', max_length=240, verbose_name='Вариант #3')),
                ('answer', models.IntegerField(verbose_name='Номер правильного ответа')),
                ('image', models.ImageField(blank=True, null=True, upload_to=tutorial.files.image_upload, verbose_name='Изображение')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=tutorial.files.thumb_upload, verbose_name='Превью')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=tutorial.files.image_upload, verbose_name='Фотография')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=tutorial.files.thumb_upload, verbose_name='Превью')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tutorial.ticket')),
            ],
        ),
    ]
